-- FieldFlow - Esquema inicial de base de datos para el MVP
-- Objetivo: implementar únicamente el modelo definido en modules-and-entities-mvp.md.
-- Motor objetivo: PostgreSQL.
--
-- Criterios de alcance:
--   * Sin auditoría transversal, soft-delete ni historial de estados.
--   * Sin tablas de usuarios/roles ni catálogo de componentes.
--   * Sin tabla de agenda: la agenda se obtiene desde assignment.
--   * Sin tabla maintenance_history: el historial se consulta desde work_order/intervention.
--   * Índices limitados a los caminos principales de consulta del MVP.

BEGIN;

-- ============================================================
-- Clients and Assets
-- ============================================================

CREATE TABLE client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL
);

CREATE TABLE site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES client(id),
    name VARCHAR(200) NOT NULL,
    address TEXT NOT NULL
);

CREATE TABLE installation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES site(id),
    name VARCHAR(200) NOT NULL
);

CREATE TABLE equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES site(id),
    installation_id BIGINT NULL REFERENCES installation(id),
    identifier VARCHAR(150) NOT NULL,
    name VARCHAR(200) NOT NULL,
    current_status VARCHAR(50) NOT NULL
);

-- Regla que no se fuerza en SQL para evitar complejidad adicional:
-- si installation_id no es NULL, la instalación debe pertenecer al mismo
-- site_id del equipo. Esta validación debe realizarse en la capa de aplicación
-- durante el MVP.

-- ============================================================
-- Work Orders
-- ============================================================

CREATE TABLE service_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL
);

CREATE TABLE work_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT NOT NULL REFERENCES equipment(id),
    service_type_id BIGINT NOT NULL REFERENCES service_type(id),
    instructions TEXT NOT NULL,
    priority VARCHAR(50) NOT NULL,
    estimated_duration INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL,

    CONSTRAINT ck_work_order_estimated_duration_positive
        CHECK (estimated_duration > 0),

    CONSTRAINT ck_work_order_status
        CHECK (status IN (
            'PENDING',
            'ASSIGNED',
            'EN_ROUTE',
            'IN_PROGRESS',
            'PENDING_CUSTOMER_CONFIRMATION',
            'COMPLETED',
            'RESCHEDULED'
        ))
);

COMMENT ON COLUMN work_order.estimated_duration IS
    'Duración estimada para planificación. La unidad debe mantenerse consistente en la aplicación.';

-- ============================================================
-- Planning and Scheduling
-- ============================================================

CREATE TABLE technician (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL
);

CREATE TABLE technician_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technician_id BIGINT NOT NULL REFERENCES technician(id),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_technician_availability_interval
        CHECK (starts_at < ends_at)
);

CREATE TABLE assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL UNIQUE REFERENCES work_order(id),
    technician_id BIGINT NOT NULL REFERENCES technician(id),
    planned_start_at TIMESTAMPTZ NOT NULL,
    planned_end_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_assignment_interval
        CHECK (planned_start_at < planned_end_at)
);

-- No se agrega una constraint para impedir solapamientos de agenda.
-- Esa regla se valida en la aplicación al asignar/reprogramar para evitar
-- introducir exclusiones de rangos y lógica SQL avanzada en el MVP.

-- ============================================================
-- Field Execution
-- ============================================================

CREATE TABLE intervention (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL REFERENCES work_order(id),
    technician_id BIGINT NOT NULL REFERENCES technician(id),
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ NULL,
    status VARCHAR(50) NOT NULL,
    result TEXT NULL,
    observations TEXT NULL,

    CONSTRAINT ck_intervention_interval
        CHECK (ended_at IS NULL OR started_at <= ended_at)
);

CREATE TABLE failure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_id BIGINT NOT NULL REFERENCES intervention(id),
    description TEXT NOT NULL
);

CREATE TABLE repair (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_id BIGINT NOT NULL REFERENCES intervention(id),
    description TEXT NOT NULL
);

CREATE TABLE intervention_component (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_id BIGINT NOT NULL REFERENCES intervention(id),
    component_name VARCHAR(200) NOT NULL,
    action VARCHAR(100) NOT NULL,
    description TEXT NULL
);

CREATE TABLE checklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL UNIQUE REFERENCES work_order(id),
    name VARCHAR(200) NOT NULL
);

CREATE TABLE checklist_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id BIGINT NOT NULL REFERENCES checklist(id),
    label TEXT NOT NULL
);

CREATE TABLE checklist_response (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_id BIGINT NOT NULL REFERENCES intervention(id),
    checklist_item_id BIGINT NOT NULL REFERENCES checklist_item(id),
    value TEXT NOT NULL,
    observation TEXT NULL,

    CONSTRAINT uq_checklist_response_intervention_item
        UNIQUE (intervention_id, checklist_item_id)
);

CREATE TABLE technical_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_id BIGINT NOT NULL REFERENCES intervention(id),
    content TEXT NOT NULL
);

-- ============================================================
-- Evidence and Conformity
-- ============================================================

CREATE TABLE evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_id BIGINT NOT NULL REFERENCES intervention(id),
    type VARCHAR(50) NOT NULL,
    reference TEXT NOT NULL,
    description TEXT NULL
);

CREATE TABLE conformity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_id BIGINT NOT NULL UNIQUE REFERENCES intervention(id),
    signature TEXT NOT NULL
);

-- ============================================================
-- Preventive Maintenance
-- ============================================================

CREATE TABLE preventive_maintenance_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT NOT NULL REFERENCES equipment(id),
    service_type_id BIGINT NOT NULL REFERENCES service_type(id),
    next_execution_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE recurrence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preventive_maintenance_plan_id BIGINT NOT NULL UNIQUE
        REFERENCES preventive_maintenance_plan(id),
    frequency VARCHAR(50) NOT NULL,
    "interval" INTEGER NOT NULL,

    CONSTRAINT ck_recurrence_interval_positive
        CHECK ("interval" > 0)
);

-- ============================================================
-- Reglas funcionales que quedan en la aplicación (MVP)
-- ============================================================
--
-- Se mantienen fuera de la base de datos porque forzarlas aquí requeriría
-- triggers, constraints compuestas o lógica de exclusión que agregaría
-- complejidad desproporcionada para el alcance actual:
--
-- 1. Si equipment.installation_id existe, esa instalación debe pertenecer
--    al mismo site_id del equipo.
-- 2. Al crear/reprogramar una assignment, validar disponibilidad del técnico
--    y evitar solapamientos de agenda.
-- 3. Un checklist_response debe responder un checklist_item perteneciente al
--    checklist de la misma work_order de la intervention.
-- 4. El cambio de work_order.status debe respetar el flujo funcional de la OT.
-- 5. Una work_order solo debe pasar a COMPLETED cuando la conformidad requerida
--    haya sido registrada.
--
-- Estas reglas deben implementarse en servicios/casos de uso de la aplicación,
-- no duplicarse mediante lógica avanzada en PostgreSQL durante el MVP.

-- ============================================================
-- Índices mínimos para los caminos críticos del MVP
-- ============================================================

-- Cliente -> sedes.
CREATE INDEX idx_site_client_id
    ON site (client_id);

-- Sede -> equipos.
CREATE INDEX idx_equipment_site_id
    ON equipment (site_id);

-- Equipo -> historial de órdenes de trabajo.
CREATE INDEX idx_work_order_equipment_id
    ON work_order (equipment_id);

-- Técnico -> agenda planificada.
CREATE INDEX idx_assignment_technician_planned_start
    ON assignment (technician_id, planned_start_at);

-- Técnico -> disponibilidad.
CREATE INDEX idx_technician_availability_technician_start
    ON technician_availability (technician_id, starts_at);

-- Orden de Trabajo -> intervenciones e historial del equipo.
CREATE INDEX idx_intervention_work_order_id
    ON intervention (work_order_id);

-- Equipo -> planes preventivos.
CREATE INDEX idx_preventive_maintenance_plan_equipment_id
    ON preventive_maintenance_plan (equipment_id);

COMMIT;
